---
title: "Assignment2 - Eli Lauwers"
output: 
  rmarkdown::github_document:
    number_sections: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library("DBI")
library("readr")
library("jsonlite")

knitr::opts_chunk$set(
  echo = TRUE
)
database_creds = read_json("database_creds.json")
database_creds[["drv"]] = RPostgres::Postgres()

con = do.call(
  RPostgres::dbConnect, 
  database_creds
)
printlines = 25
```

# Interpretation of advanced SQL

## Consider the folowing `SELECT`-query

```{sql connection=con}
SELECT DISTINCT license_plate
FROM registration r1
WHERE NOT EXISTS(
  SELECT 1
  FROM registration r2
  WHERE r1.email != r2.email
  AND r1.license_plate = r2.license_plate
)
```
**Question**: Describe, in your own words, what this SELECT-query achieves. You should not give the result table of this query or explain this query in technical terms (i.e. we do not expect a literal translation of the operations that are performed in the query), but explain what the semantical outcome is of this query when executed on data that is stored in the rollsrobin database. Provide your answer in a short report.

**Argumentation**: When interpreting SQL-queries with subqueries, I always try to interpret the subquery first. In this case however, the subquery uses the `registration r1` as provided in the subquery.

The subquery returns all registrations where different `email` adresses where used on the same `license_plate`. In other words, it returns a __subtable__ with cars that have been rented by multiple different people. In the outer query, all `registrations` are checked against that subtable. By using a `NOT EXISTS` clause, the resulting table consists of all registrations where a car was rented by only one person. It can however be that the car in question was rented multiple times. 

Lastly, the `SELECT DISTINCT license_plate` states that we will extract every distinct license_plate. So in other words: from all cars that are rented by only one person, get the license plates.

In summary, the full query returns all `lincense_plates` from cars that were indeed rented, but only rented by one person.

**Check**: To check my working hypothesis, I will create an SQL query that will result in a subset of license_plates from cars that were rented by one distinct person (cf. my working hypothesis). The resulting table shows the exact same subset of `license_plates` which validates - or provides extra evidence - for the hypothesis.

```{sql connection=con, code = readLines("ass2_check.sql")}

```

**Answer**: The query returns all `lincense_plates` from cars that were rented by only one distinct person.

## Rewrite

**Question**: Rewrite the following SELECT-query such that it does not use aggregation functions, grouping and having. However, it is important that the result table retrieved by your query equals exactly the result table retrieved by the original query, so try to understand the original query first. Add a file with the name studentcode_firstname_lastname_1_2.sql, in which you substitute ‘studentcode’, ‘firstname’ and ‘lastname’ by resp. your studentcode, firstname and lastname, to the .zip file containing the rewritten SELECT-query.

```{sql connection=con}
SELECT DISTINCT r.email 
FROM registration r
INNER JOIN car c USING (license_plate)
GROUP BY r.email
HAVING COUNT(DISTINCT c.enterprisenumber) = 1;
```

**Argumentation**: Interpretation of the code is as follows: 'Return all distinct email adressess of people who have rented cars at only one distinct enterprise(number)'. So I'll create some SQL code doing the exact same thing.

```{sql connection = con, code = readLines("01504786_eli_lauwers_1_2.sql")}

```

## Consider the following task for which a SELECT-query should be written.

**Question**: Give a list of email addresses of all persons (one or multiple) who registered a car for the longest rental period present in the database. Here, the length of a rental period is based on the number of days from period_begin until period_end (boundaries inclusive).

Only persons who started this (longest) rental period the earliest (based on period_begin) of all people renting for the longest period should be returned by your query. In the result table, only one column email of datatype varchar is expected.

Now have a look at the following SELECT-query.

```{sql connection = con, eval=F}
SELECT DISTINCT email 
FROM registration 
INNER JOIN person USING (email)
WHERE period_end - period_begin >= ALL (
    SELECT period_end - period_begin FROM registration
  )
AND period_begin <= ALL (SELECT period_begin FROM registration);
```

Does this query solve the task that was described above in all possible situations? If not, explain in your own words what is wrong with the query and how you can solve this. Provide your answer in a short report.

**Argumentation**: The problem lies in the `AND` clause. Right now, the resuting table consists of all rows where the renting period was the longest **and** where the begin date of the rental period comes before all other dates. The only time the query will work is if the longest rental period belongs to the rental period which also started before all other registrations. Running this query on the testset won't work probably. Also, the fourth row states that `person2@ugent.be` only rented 5 days, when the rental dates are nearly a year apart. Seems like a little mistake. 

I would advise altering the query by integrating a subquery. 

- in the subquery, select all rows with the maximum renting period
- in the outer query, return the earliest starter from the subquery.

```{sql connection = con}
/*
  From the people who rented a car for the longest time in the db, 
  Get the email adres of the person(s) who started their rental on the
  earliest date
  
  First, get all rentals that where the longest in the database
  Then, find the earliest date in that subtable
  
*/
SELECT DISTINCT tmp.email
FROM ( -- Subquery: get the rows with maximum rental period
    SELECT *
    FROM registration r
    WHERE r.period_end - r.period_begin >= ALL(
    SELECT r.period_end - r.period_begin FROM registration r
  )
) tmp
WHERE tmp.period_begin <= ALL( --Subquery: get the rows with maximum rental period
    SELECT r.period_begin
    FROM registration r
    WHERE r.period_end - r.period_begin >= ALL(
      SELECT r.period_end - r.period_begin FROM registration r
    )
)
```

# Advanced SQL

Provide SQL SELECT-queries as solutions to the following exercises related to the rollsrobin database. Each query should be added to a separate .sql file with filename studentcode_firstname_lastname_2_X.sql in which you substitute ‘studentcode’, ‘firstname’ and ‘lastname’ with your studentcode, firstname and lastname respectively, and ‘X’ with the number of the question (1 to 5). Add these .sql files to your final .zip file.

## passed nights between rentals

**Question**: Give for each car in the database that was rented (registered) at least once, the number of nights that passed by between the first time that the car was rented (based on period_begin of the first registration, exclusive) and the last time that the car was rented (based on period_begin of the last registration, inclusive). In the result table, we expect two columns with corresponding datatype: license_plate (varchar) and passed_nights (integer). 

**Answer**:

```{sql connection = con, code = readLines("01504786_eli_lauwers_2_1.sql")}

```

## Employee with most rents

**Question**: Give the employee who rented the highest number of unique cars (so, not the employee that did the highest number of unique car rentals). In the result table, we expect one column with name email and datatype varchar. Make sure that your query takes into account ex aequos.

```{sql connection = con, code = readLines("01504786_eli_lauwers_2_2.sql")}

```

## Employee longest rental during his contract

**Question**: Give, for each car brand (so not car model), the total number of times that an employee rented a car of this brand himself/herself during his/her contract at the same company that owns the rented car (i.e. registration.period_begin should be between contract.period_begin and contract.period_end, boundaries inclusive). In the result table, we expect two columns with corresponding datatype: brand (varchar) and amount (integer). Also include brands that are persisted in the database and for which no car rental meets the requirements, with an amount of 0. Sort the results first on amount (numerically descending) and then on brand (alphabetically ascending).

**Answer**:

```{sql connection = con, code = readLines("01504786_eli_lauwers_2_3.sql")}

```

## percentage employees and percentage cars

**Question**: Calculate, for each email domain used by an employee, two different numerical values, which are

- the percentage share of unique employees using this email domain on the total number of unique persons (i.e. employees and non-employees) using this email domain (column percentage_employees), and 
- the percentage share of unique cars rented by employees using this email domain on the total number of unique cars rented by persons (i.e. employees and non-employees) using this email domain (column percentage_cars). 

You may assume that domains in an email address start right after the ‘@’ symbol (and that there is only one ‘@’ symbol in an email address) and end right before the final ‘.’ symbol (e.g. gmail, hotmail,. . . ). Besides that, you may also assume that all persons did at least one registration. So, in the result table, we expect three columns with corresponding datatype: email_domain (varchar), percentage_employees (numeric) and percentage_cars (numeric). The values in columns percentage_employees and percentage_cars should be between 0 and 100 (boundaries inclusive) and should be rounded up to two decimals

**Answer**:

```{sql connection = con, code = readLines("01504786_eli_lauwers_2_4.sql")}

```

## Absolute deviation

**Question**: Return the license plate of the car of which the total number of times that this car was rented, is the closest to the average number of times that a car is rented (computed over all cars present in the database). Be aware of the fact that, in order to calculate the average, you should also take into account the cars that have never been rented before. In the result table, only one column license_plate of datatype varchar is expected. Make sure that your query takes into account ex aequos.

**Answer**:

```{sql connection = con, code = readLines("01504786_eli_lauwers_2_5.sql")}

```
